const data=window.REGHEEF_MENU;let lang='ar';
const money=v=>typeof v==='object'?v[lang]:`${v} ${lang==='ar'?'ج.م':'EGP'}`;
const t=(obj,k)=>obj[k+'_'+lang]||obj[k]||'';
function shuffle(arr){return [...arr].sort(()=>Math.random()-0.5)}
const featuredPick=shuffle((data.featured||[]).filter(f=>f.image)).slice(0,2);
function setLang(l){lang=l;renderMenu();setTimeout(()=>document.querySelector('.topbar')?.scrollIntoView({behavior:'smooth'}),80)}
function hero(){const img=data.heroImages[0]||'';return `<section class="hero" style="--hero:url('${img}')"><div class="hero-inner ${lang==='ar'?'rtl':''}"><img class="logo" src="assets/logo/logo-cream.png" alt="Regheef"><h1>${lang==='ar'?'فطار بمزاج':'Breakfast with a mood'}</h1><p>${lang==='ar'?'اختار اللغه علشان تشوف المنيو':'Choose your preferred language and browse the menu'}</p><div class="language"><button class="btn primary" onclick="setLang('ar')">العربية</button><button class="btn secondary" onclick="setLang('en')">English</button></div></div></section>`}
function renderMenu(){document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';let cats=data.sections.filter(s=>s.items.length && s.id!=='بدون' && s.ar!=='بدون' && s.en!=='Without');const featured=featuredPick.length?featuredPick:(data.featured||[]).filter(f=>f.image).slice(0,2);document.getElementById('app').innerHTML=`${hero()}<div class="topbar"><div class="topbar-inner"><img src="assets/logo/logo-green.png" alt="Regheef"><div class="lang-switch"><button class="chip" onclick="setLang('ar')">عربي</button><button class="chip" onclick="setLang('en')">EN</button></div></div></div><main class="main ${lang==='ar'?'rtl':''}"><h2 class="section-title">${lang==='ar'?'اختيارات مميزة':'Featured Picks'}</h2><div class="featured">${featured.map(it=>`<article class="feature-card"><img src="${it.image}" loading="lazy" alt="${lang==='ar'?it.ar:it.en}"/><div><h3>${lang==='ar'?it.ar:it.en}</h3><p>${it.prices[0]?money(it.prices[0].value):''}</p></div></article>`).join('')}</div><nav class="tabs">${cats.map(s=>`<a href="#${s.id}">${lang==='ar'?s.ar:s.en}</a>`).join('')}</nav>${cats.map(section).join('')}</main>${footer()}`}
function section(s){return `<section id="${s.id}"><h2 class="section-title">${lang==='ar'?s.ar:s.en}</h2><div class="menu-grid">${s.items.map(card).join('')}</div></section>`}
function card(it){const imageHtml=it.image?`<div class="pic"><img src="${it.image}" loading="lazy" alt="${lang==='ar'?it.ar:it.en}"></div>`:'';return `<article class="card ${it.image?'':'no-img'}">${imageHtml}<div><h3>${lang==='ar'?it.ar:it.en}</h3><div class="prices">${it.prices.map(p=>`<span class="price">${lang==='ar'?p.label_ar:p.label_en}: <b>${money(p.value)}</b></span>`).join('')}</div>${(lang==='ar'?it.note_ar:it.note_en)?`<p class="note">${lang==='ar'?it.note_ar:it.note_en}</p>`:''}</div></article>`}
function footer(){return `<footer class="${lang==='ar'?'rtl':''}"><div class="footer-inner"><img class="footer-logo" src="assets/logo/logo-cream.png" alt="Regheef"><p class="meta">${lang==='ar'?data.brand.address_ar:data.brand.address_en}<br>${data.brand.phone}</p><div class="foot-actions"><a href="${data.brand.maps}" target="_blank">${lang==='ar'?'الموقع':'Location'}</a><a href="tel:${data.brand.phone}">${lang==='ar'?'اتصل بنا':'Call us'}</a><a href="${data.brand.instagram}" target="_blank">Instagram</a><a href="${data.brand.facebook}" target="_blank">Facebook</a><a href="${data.brand.tiktok}" target="_blank">TikTok</a></div></div></footer>`}
renderMenu();
